### ISSUE TITLE
Implement a shell so running the scicmd command is not needed

### ISSUE THREAD

**Issue by alneberg** [samuell/scicommander#2]
Hello!

Thank you for the discussion yesterday. I found that at least `zsh` has [hooks](https://github.com/rothgar/mastering-zsh/blob/master/docs/config/hooks.md), specifically `preexec` that will run before the command is executed and will (if history is enabled I believe) get the command as an input.

This isn't really an issue so feel free to close it as soon as you want.

**Comment by samuell** [comment]
Thanks a lot @alneberg , appreciate the tip a lot! This is a great pointer, and I'll have a look and see if there are some general mechanism that would work in many different shells.

**Comment by samuell** [comment]
I just found out about the [cmd](https://code-maven.com/interactive-shell-with-cmd-in-python) module in the Python standard library that seems to be able to do this!
